{% set name = "compas_mobile_robot_reloc" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6f2a1f6a1353e874fc58c0343f1d39350b1fb1aa81e0cd18d1c84894c5d514d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
    - wheel
  run:
    - compas >=0.17.2,<1.3
    - python >=3.7

test:
  imports:
    - compas_mobile_robot_reloc
    - compas_mobile_robot_reloc.utils
    - compas_mobile_robot_reloc.xforms
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest -vv tests

about:
  home: https://gramaziokohler.github.io/compas_mobile_robot_reloc
  summary: Robot localization using external measuring device (total station).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tetov
